import { forwardRef, useImperativeHandle } from "react";
import { IMAGE_BASE_URL } from "@/utils/api";

const FollowupDetailsPrint = forwardRef((props, ref) => {
    useImperativeHandle(ref, () => ({
        print: () => {
            const element = document.getElementById("followupTable");
            if (!element) return alert("Followup Table not found!");

            const rows = Array.from(element.querySelectorAll("tbody tr"));
            const tableHeaderHTML = element.querySelector("thead").outerHTML;

            const rowsPerPage = 30;
            const pagesHTML = [];

            for (let i = 0; i < rows.length; i += rowsPerPage) {
                let chunkRows = rows
                    .slice(i, i + rowsPerPage)
                    .map((r) => r.outerHTML)
                    .join("");

                // ⭐ APPLY DESCRIPTION COLUMN CLASS (250px width + justify)
                chunkRows = chunkRows.replaceAll(
                    "<td>",
                    '<td class="description-col">'
                );

                pagesHTML.push(`
          <div class="page">

            <!-- HEADER -->
            <div class="print-header">
              <div class="company-name">${props.companyName || ""}</div>
              <div class="sub-header">Followup Details Print</div>
              <div class="logo-box">
                <img src="${IMAGE_BASE_URL}${props.companyLogo}" alt="Logo" style="width:150px"/>
              </div>
            </div>

            <!-- CONTENT -->
            <div class="content">
              <table>
                ${tableHeaderHTML}
                <tbody>${chunkRows}</tbody>
              </table>
            </div>

            <!-- FOOTER -->
            <div class="print-footer">
              <div class="company">Generated by ${props.companyName || ""}</div>
              <img src="${IMAGE_BASE_URL}${props.companyLogo}" class="footer-logo" alt="Footer Logo" />
            </div>

          </div>
        `);
            }

            const printWindow = window.open("", "_blank");
            printWindow.document.write(`
        <html>
          <head>
            <style>
              body {
                font-family: Arial, sans-serif;
                margin: 0;
                padding: 0;
              }

              @media print {
                @page { size: A4; margin: 0; }
                .page { page-break-after: always; position: relative; min-height: 297mm; }
              }

              .print-header {
                position: fixed;
                top: 0;
                left: 0;
                right: 0;
                text-align: center;
                padding: 10px 0;
                border-bottom: 1px solid #ccc;
                background: white;
              }

              .print-footer {
                position: fixed;
                bottom: 0;
                left: 0;
                right: 0;
                text-align: center;
                padding: 5px 0;
                font-size: 12px;
                border-top: 1px solid #ccc;
                background: white;
              }

              .content {
                margin-top: 160px;
                margin-bottom: 80px;
              }

              table {
                width: 100%;
                border-collapse: collapse;
                font-size: 14px;
              }

              th, td {
                border: 1px solid #ddd;
                padding: 8px;
              }

              /* ⭐ DESCRIPTION COLUMN FIX */
              td.description-col {
                width: 250px;
                white-space: normal !important;
                word-wrap: break-word;
                text-align: justify;
              }

              th {
                background: #053054;
                color: white;
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
              }

              tr:nth-child(even) {
                background: #f9f9f9;
              }

              .company-name { font-size: 22px; font-weight: bold; color: #053054; }
              .company { font-weight: bold; color: #053054; }
              .sub-header { font-size: 16px; font-weight: bold; margin-top: 5px; color: #444; }
              .logo-box img { width: 150px; height: auto; margin-top: 10px; }
              .footer-logo { width: 60px; height: auto; margin-top: 5px; }
            </style>
          </head>

          <body>
            ${pagesHTML.join("")}
          </body>
        </html>
      `);

            printWindow.document.close();
            setTimeout(() => {
                printWindow.print();
                printWindow.close();
            }, 500);
        },
    }));

    return null;
});

export default FollowupDetailsPrint;
