import { forwardRef, useImperativeHandle } from "react";
import { IMAGE_BASE_URL } from "@/utils/api";

const PaymentsChartsPrint = forwardRef((props, ref) => {
  useImperativeHandle(ref, () => ({
    print: () => {
      const chartEl = document.getElementById("paymentsChart");
      if (!chartEl) return alert("Payments Chart not found!");

      const children = Array.from(chartEl.children);

      // Group charts into pairs (two per page)
      const pages = [];
      for (let i = 0; i < children.length; i += 2) {
        const pair = children.slice(i, i + 2);
        pages.push(pair);
      }

      const pagesHTML = pages
        .map((pair) => {
          const chartsHTML = pair
            .map((child) => `
              <div class="chart-container">
                ${child.outerHTML}
              </div>
            `)
            .join("");

          return `
            <div class="print-page">
              <!-- HEADER -->
              <div class="print-header">
                <div class="company-name">${props.companyName || ""}</div>
                <div class="sub-header">Payments Charts Print</div>
                <div class="logo-box">
                  <img src="${IMAGE_BASE_URL}${props.companyLogo}" alt="Logo" />
                </div>
              </div>

              <!-- CONTENT - two charts side by side or stacked -->
              <div class="page-content">
                ${chartsHTML}
              </div>

              <!-- FOOTER -->
              <div class="print-footer">
                <div class="company">Generated by ${props.companyName || ""}</div>
                <img src="${IMAGE_BASE_URL}${props.companyLogo}" class="footer-logo" alt="Footer Logo" />
              </div>
            </div>
          `;
        })
        .join("");

      const printWindow = window.open("", "_blank");

      printWindow.document.write(`
        <html>
          <head>
            <style>
              body {
                font-family: Arial, sans-serif;
                margin: 0;
                padding: 0;
              }

              @media print {
                @page {
                  size: A4 portrait;
                  margin: 0 !important;
                }

                .print-page {
                  page-break-after: always;
                  width: 100%;
                  height: 100vh;
                  display: flex;
                  flex-direction: column;
                  align-items: center;
                  justify-content: space-between;
                  box-sizing: border-box;
                }

                .print-page:last-child {
                  page-break-after: auto;
                }
              }

              .print-header {
                position: fixed;
                top: 0;
                left: 0;
                right: 0;
                text-align: center;
                padding: 12px 0;
                border-bottom: 1px solid #ccc;
                background: white;
                z-index: 10;
              }

              .print-footer {
                position: fixed;
                bottom: 0;
                left: 0;
                right: 0;
                text-align: center;
                padding: 8px 0;
                font-size: 11px;
                border-top: 1px solid #ccc;
                background: white;
                z-index: 10;
              }

              .footer-logo {
                width: 60px;
                height: auto;
                margin-top: 4px;
              }

              .company-name {
                font-size: 22px;
                font-weight: bold;
                color: #053054;
              }
              .company {
                font-weight: bold;
                color: #053054;
              }

              .sub-header {
                font-size: 16px;
                font-weight: bold;
                margin-top: 6px;
                color: #444;
              }

              .logo-box img {
                width: 140px;
                height: auto;
                margin-top: 8px;
              }

              .page-content {
                margin-top: 200px;
                margin-bottom: 80px;
                width: 100%;
                max-width: 1000px;
                display: flex;
                flex-direction: column;
                align-items: center;
                gap: 60px;
              }

              .chart-container {
                width: 100%;
                max-width: 900px;
                text-align: center;
              }

              .recharts-wrapper {
                margin: 0 auto !important;
              }
            </style>
          </head>

          <body>
            ${pagesHTML}
          </body>
        </html>
      `);

      printWindow.document.close();

      setTimeout(() => {
        printWindow.focus();
        printWindow.print();
      }, 800);
    },
  }));

  return null;
});

export default PaymentsChartsPrint;