import { forwardRef, useImperativeHandle } from "react";
import { IMAGE_BASE_URL } from "@/utils/api";

const OrderChartsPrint = forwardRef((props, ref) => {
    useImperativeHandle(ref, () => ({
        print: () => {
            const chartEl = document.getElementById("orderChart");
            if (!chartEl) return alert("Order Chart not found!");

            const printWindow = window.open("", "_blank");

            const chartItems = Array.from(chartEl.children);

            // Group charts into pairs (2 per page)
            const pageGroups = [];
            for (let i = 0; i < chartItems.length; i += 2) {
                pageGroups.push(chartItems.slice(i, i + 2));
            }

            // Build final HTML for printing
            const pagesHTML = pageGroups
                .map(
                    (charts) => `
                    <div class="print-page">
                        <!-- HEADER -->
                        <div class="print-header">
                            <div class="company-name">${props.companyName || ""}</div>
                            <div class="sub-header">Order Charts Print</div>
                            <div class="logo-box">
                                <img src="${IMAGE_BASE_URL}${props.companyLogo}" alt="Logo" />
                            </div>
                        </div>

                        <!-- CONTENT (TWO CHARTS WITH 40PX GAP) -->
                        <div class="page-content">
                            ${charts.map((c) => c.outerHTML).join("")}
                        </div>

                        <!-- FOOTER -->
                        <div class="print-footer">
                            <div class="company">Generated by ${props.companyName || ""}</div>
                            <img src="${IMAGE_BASE_URL}${props.companyLogo}" class="footer-logo" alt="Footer Logo" />
                        </div>
                    </div>
                `
                )
                .join("");

            printWindow.document.write(`
                <html>
                    <head>
                        <style>
                            body {
                                font-family: Arial, sans-serif;
                                margin: 0;
                                padding: 0;
                            }

                            @media print {
                                @page {
                                    size: A4;
                                    margin: 0 !important;
                                }

                                .print-page {
                                    page-break-after: always;
                                    width: 100%;
                                    min-height: 100vh;
                                    display: flex;
                                    flex-direction: column;
                                    align-items: center;
                                    position: relative;
                                }

                                .print-page:last-child {
                                    page-break-after: auto;
                                }
                            }

                            .print-header {
                                position: fixed;
                                top: 0;
                                left: 0;
                                right: 0;
                                text-align: center;
                                padding: 10px 0;
                                border-bottom: 1px solid #ccc;
                                background: white;
                            }

                            .print-footer {
                                position: fixed;
                                bottom: 0;
                                left: 0;
                                right: 0;
                                text-align: center;
                                padding: 5px 0;
                                font-size: 12px;
                                border-top: 1px solid #ccc;
                                background: white;
                            }

                            .footer-logo {
                                width: 60px;
                                height: auto;
                                margin-top: 5px;
                            }

                            .company-name {
                                font-size: 22px;
                                font-weight: bold;
                                color: #053054;
                            }

                            .company {
                                font-weight: bold;
                                color: #053054;
                            }

                            .sub-header {
                                font-size: 16px;
                                font-weight: bold;
                                margin-top: 5px;
                                color: #444;
                            }

                            .logo-box img {
                                width: 150px;
                                height: auto;
                                margin-top: 10px;
                            }

                            /* TWO CHARTS WITH 40PX GAP */
                            .page-content {
                                margin-top: 200px;
                                margin-bottom: 80px;
                                width: 100%;
                                text-align: center;
                                display: flex;
                                flex-direction: column;
                                gap: 200px; /* <-- EXACT GAP YOU REQUESTED */
                                align-items: center;
                            }

                            table {
                                width: 100%;
                                border-collapse: collapse;
                                font-size: 14px;
                            }

                            th, td {
                                border: 1px solid #ddd;
                                padding: 8px;
                                white-space: nowrap;
                            }

                            th {
                                background: #053054 !important;
                                color: white !important;
                                -webkit-print-color-adjust: exact !important;
                                print-color-adjust: exact !important;
                            }

                            tr:nth-child(even) {
                                background: #f9f9f9;
                            }
                        </style>
                    </head>

                    <body>
                        ${pagesHTML}
                    </body>
                </html>
            `);

            printWindow.document.close();

            setTimeout(() => {
                printWindow.print();
                printWindow.close();
            }, 500);
        },
    }));

    return null;
});

export default OrderChartsPrint;
