// Auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const VERIFY_TOKEN_SUCCESS = "VERIFY_TOKEN_SUCCESS";
export const VERIFY_TOKEN_FAIL = "VERIFY_TOKEN_FAIL";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const SET_USER = "SET_USER";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const PACKAGE_SELECT_SUCCESS = "PACKAGE_SELECT_SUCCESS";
export const PACKAGE_SELECT_FAIL = "PACKAGE_SELECT_FAIL";
export const GET_ORGANIZATION_INFO_SUCCESS = "GET_ORGANIZATION_INFO_SUCCESS";
export const GET_ORGANIZATION_INFO_FAIL = "GET_ORGANIZATION_INFO_FAIL";
export const PROVIDER_REGISTER_ORG_SUCCESS = "PROVIDER_REGISTER_ORG_SUCCESS";
export const PROVIDER_REGISTER_ORG_FAIL    = "PROVIDER_REGISTER_ORG_FAIL";

// Company Setup
export const GET_COMPANY_SETUP = "GET_COMPANY_SETUP";
export const UPDATE_COMPANY_SETUP = "UPDATE_COMPANY_SETUP";
export const UPLOAD_COMPANY_LOGO = "UPLOAD_COMPANY_LOGO";
export const REMOVE_COMPANY_LOGO = "REMOVE_COMPANY_LOGO";
export const COMPANY_SETUP_LOADING = "COMPANY_SETUP_LOADING";
export const COMPANY_SETUP_ERROR = "COMPANY_SETUP_ERROR";
export const COMPANY_SETUP_SUCCESS = "COMPANY_SETUP_SUCCESS";

// Landing Page Setup
export const GET_LANDING_PAGE_SETUP = "GET_LANDING_PAGE_SETUP";
export const UPDATE_LANDING_PAGE_SETUP = "UPDATE_LANDING_PAGE_SETUP";
export const LANDING_PAGE_SETUP_LOADING = "LANDING_PAGE_SETUP_LOADING";
export const LANDING_PAGE_SETUP_SUCCESS = "LANDING_PAGE_SETUP_SUCCESS";
export const LANDING_PAGE_SETUP_ERROR = "LANDING_PAGE_SETUP_ERROR";

// Assigned Incentives
export const GET_ASSIGNED_INCENTIVES = "GET_ASSIGNED_INCENTIVES";
export const CREATE_ASSIGNED_INCENTIVE = "CREATE_ASSIGNED_INCENTIVE";
export const UPDATE_ASSIGNED_INCENTIVE = "UPDATE_ASSIGNED_INCENTIVE";
export const DELETE_ASSIGNED_INCENTIVE = "DELETE_ASSIGNED_INCENTIVE";
export const ASSIGNED_INCENTIVES_LOADING = "ASSIGNED_INCENTIVES_LOADING";
export const ASSIGNED_INCENTIVES_SUCCESS = "ASSIGNED_INCENTIVES_SUCCESS";
export const ASSIGNED_INCENTIVES_ERROR = "ASSIGNED_INCENTIVES_ERROR";

// Profile
export const GET_PROFILE = "GET_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const UPLOAD_PROFILE_IMAGE = "UPLOAD_PROFILE_IMAGE";
export const REMOVE_PROFILE_IMAGE = "REMOVE_PROFILE_IMAGE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";

// RBAC
export const GET_MODULES = "GET_MODULES";
export const ADD_MODULE = "ADD_MODULE";
export const GET_PERMISSIONS = "GET_PERMISSIONS";
export const GET_PERMISSIONSOFROLE = "GET_PERMISSIONSOFROLE";
export const GET_PERMISSIONSMAPPED = "GET_PERMISSIONSMAPPED";
export const GET_ROLES = "GET_ROLES";
export const ADD_ROLE = "ADD_ROLE";
export const UPDATE_ROLE = "UPDATE_ROLE";
export const UPDATE_MODULE = "UPDATE_MODULE";
export const DELETE_ROLE = "DELETE_ROLE";
export const DELETE_MODULE = "DELETE_MODULE";
export const RBAC_LOADING = "RBAC_LOADING";
export const RBAC_ERROR = "RBAC_ERROR";
export const RBAC_SUCCESS = "RBAC_SUCCESS";

// Salutation
export const GET_SALUTATIONS = "GET_SALUTATIONS";
export const ADD_SALUTATION = "ADD_SALUTATION";
export const UPDATE_SALUTATION = "UPDATE_SALUTATION";
export const DELETE_SALUTATION = "DELETE_SALUTATION";
export const SALUTATION_LOADING = "SALUTATION_LOADING";
export const SALUTATION_ERROR = "SALUTATION_ERROR";
export const SALUTATION_SUCCESS = "SALUTATION_SUCCESS";

// Lead Status
export const GET_STATUS = "GET_STATUS";
export const ADD_STATUS = "ADD_STATUS";
export const UPDATE_STATUS = "UPDATE_STATUS";
export const DELETE_STATUS = "DELETE_STATUS";
export const STATUS_LOADING = "STATUS_LOADING";
export const STATUS_ERROR = "STATUS_ERROR";
export const STATUS_SUCCESS = "STATUS_SUCCESS";

// Lead Stage
export const GET_STAGE = "GET_STAGE";
export const ADD_STAGE = "ADD_STAGE";
export const UPDATE_STAGE = "UPDATE_STAGE";
export const DELETE_STAGE = "DELETE_STAGE";
export const STAGE_LOADING = "STAGE_LOADING";
export const STAGE_ERROR = "STAGE_ERROR";
export const STAGE_SUCCESS = "STAGE_SUCCESS";

// Lead Source
export const GET_SOURCE = "GET_SOURCE";
export const ADD_SOURCE = "ADD_SOURCE";
export const UPDATE_SOURCE = "UPDATE_SOURCE";
export const DELETE_SOURCE = "DELETE_SOURCE";
export const SOURCE_LOADING = "SOURCE_LOADING";
export const SOURCE_ERROR = "SOURCE_ERROR";
export const SOURCE_SUCCESS = "SOURCE_SUCCESS";

// product brand
export const GET_PRODUCT_BRAND = "GET_PRODUCT_BRAND";
export const ADD_PRODUCT_BRAND = "ADD_PRODUCT_BRAND";
export const UPDATE_PRODUCT_BRAND = "UPDATE_PRODUCT_BRAND";
export const DELETE_PRODUCT_BRAND = "DELETE_PRODUCT_BRAND";
export const PRODUCT_BRAND_LOADING = "PRODUCT_BRAND_LOADING";
export const PRODUCT_BRAND_ERROR = "PRODUCT_BRAND_ERROR";
export const PRODUCT_BRAND_SUCCESS = "PRODUCT_BRAND_SUCCESS";

// product category
export const GET_PRODUCT_CATEGORY = "GET_PRODUCT_CATEGORY";
export const ADD_PRODUCT_CATEGORY = "ADD_PRODUCT_CATEGORY";
export const UPDATE_PRODUCT_CATEGORY = "UPDATE_PRODUCT_CATEGORY";
export const DELETE_PRODUCT_CATEGORY = "DELETE_PRODUCT_CATEGORY";
export const PRODUCT_CATEGORY_LOADING = "PRODUCT_CATEGORY_LOADING";
export const PRODUCT_CATEGORY_ERROR = "PRODUCT_CATEGORY_ERROR";
export const PRODUCT_CATEGORY_SUCCESS = "PRODUCT_CATEGORY_SUCCESS";

// product sub category
export const GET_PRODUCT_SUB_CATEGORY = "GET_PRODUCT_SUB_CATEGORY";
export const ADD_PRODUCT_SUB_CATEGORY = "ADD_PRODUCT_SUB_CATEGORY";
export const UPDATE_PRODUCT_SUB_CATEGORY = "UPDATE_PRODUCT_SUB_CATEGORY";
export const DELETE_PRODUCT_SUB_CATEGORY = "DELETE_PRODUCT_SUB_CATEGORY";
export const PRODUCT_SUB_CATEGORY_LOADING = "PRODUCT_SUB_CATEGORY_LOADING";
export const PRODUCT_SUB_CATEGORY_ERROR = "PRODUCT_SUB_CATEGORY_ERROR";
export const PRODUCT_SUB_CATEGORY_SUCCESS = "PRODUCT_SUB_CATEGORY_SUCCESS";

// product unit
export const GET_PRODUCT_UNIT = "GET_PRODUCT_UNIT";
export const ADD_PRODUCT_UNIT = "ADD_PRODUCT_UNIT";
export const UPDATE_PRODUCT_UNIT = "UPDATE_PRODUCT_UNIT";
export const DELETE_PRODUCT_UNIT = "DELETE_PRODUCT_UNIT";
export const PRODUCT_UNIT_LOADING = "PRODUCT_UNIT_LOADING";
export const PRODUCT_UNIT_ERROR = "PRODUCT_UNIT_ERROR";
export const PRODUCT_UNIT_SUCCESS = "PRODUCT_UNIT_SUCCESS";

// product
export const GET_PRODUCT = "GET_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";

// Country
export const GET_COUNTRY = "GET_COUNTRY";
export const ADD_COUNTRY = "ADD_COUNTRY";
export const UPDATE_COUNTRY = "UPDATE_COUNTRY";
export const DELETE_COUNTRY = "DELETE_COUNTRY";
export const COUNTRY_LOADING = "COUNTRY_LOADING";
export const COUNTRY_ERROR = "COUNTRY_ERROR";
export const COUNTRY_SUCCESS = "COUNTRY_SUCCESS";

// Country Code
export const GET_COUNTRY_CODE = "GET_COUNTRY_CODE";
export const ADD_COUNTRY_CODE = "ADD_COUNTRY_CODE";
export const UPDATE_COUNTRY_CODE = "UPDATE_COUNTRY_CODE";
export const DELETE_COUNTRY_CODE = "DELETE_COUNTRY_CODE";
export const COUNTRY_CODE_LOADING = "COUNTRY_CODE_LOADING";
export const COUNTRY_CODE_ERROR = "COUNTRY_CODE_ERROR";
export const COUNTRY_CODE_SUCCESS = "COUNTRY_CODE_SUCCESS";

// Country Currency
export const GET_CURRENCY = "GET_CURRENCY";
export const ADD_CURRENCY = "ADD_CURRENCY";
export const UPDATE_CURRENCY = "UPDATE_CURRENCY";
export const DELETE_CURRENCY = "DELETE_CURRENCY";
export const CURRENCY_LOADING = "CURRENCY_LOADING";
export const CURRENCY_ERROR = "CURRENCY_ERROR";
export const CURRENCY_SUCCESS = "CURRENCY_SUCCESS";

// Zones
export const GET_ZONES = "GET_ZONES";
export const ADD_ZONES = "ADD_ZONES";
export const UPDATE_ZONES = "UPDATE_ZONES";
export const DELETE_ZONES = "DELETE_ZONES";
export const ZONE_LOADING = "ZONE_LOADING";
export const ZONE_ERROR = "ZONE_ERROR";
export const ZONE_SUCCESS = "ZONE_SUCCESS";

// Employees
export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const EMPLOYEE_LOADING = "EMPLOYEE_LOADING";
export const EMPLOYEE_ERROR = "EMPLOYEE_ERROR";
export const EMPLOYEE_SUCCESS = "EMPLOYEE_SUCCESS";

// Customers
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const CUSTOMER_LOADING = "CUSTOMER_LOADING";
export const CUSTOMER_ERROR = "CUSTOMER_ERROR";
export const CUSTOMER_SUCCESS = "CUSTOMER_SUCCESS";

// Lead & Followup
export const GET_LEADS = "GET_LEADS";
export const ADD_LEAD = "ADD_LEAD";
export const UPDATE_LEAD = "UPDATE_LEAD";
export const DELETE_LEAD = "DELETE_LEAD";
export const DELETE_LEAD_FILE = "DELETE_LEAD_FILE";
export const LEAD_LOADING = "LEAD_LOADING";
export const LEAD_SUCCESS = "LEAD_SUCCESS";
export const LEAD_ERROR = "LEAD_ERROR";
export const ADD_FOLLOWUP = "ADD_FOLLOWUP";
export const GET_FOLLOWUPS = "GET_FOLLOWUPS";
export const UPDATE_FOLLOWUP = "UPDATE_FOLLOWUP";
export const DELETE_FOLLOWUP = "DELETE_FOLLOWUP";
export const FOLLOWUP_LOADING = "FOLLOWUP_LOADING";
export const FOLLOWUP_SUCCESS = "FOLLOWUP_SUCCESS";
export const FOLLOWUP_ERROR = "FOLLOWUP_ERROR";

// Quotation
export const GET_QUOTATIONS = "GET_QUOTATIONS";
export const ADD_QUOTATION = "ADD_QUOTATION";
export const UPDATE_QUOTATION = "UPDATE_QUOTATION";
export const DELETE_QUOTATION = "DELETE_QUOTATION";
export const QUOTATION_LOADING = "QUOTATION_LOADING";
export const QUOTATION_SUCCESS = "QUOTATION_SUCCESS";
export const QUOTATION_ERROR = "QUOTATION_ERROR";

// Order
export const GET_ORDERS = "GET_ORDERS";
export const ADD_ORDER = "ADD_ORDER";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";
export const ORDER_LOADING = "ORDER_LOADING";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_ERROR = "ORDER_ERROR";

// Order Status
export const GET_ORDER_STATUS = "GET_ORDER_STATUS";
export const ADD_ORDER_STATUS = "ADD_ORDER_STATUS";
export const UPDATE_ORDER_STATUS = "UPDATE_ORDER_STATUS";
export const DELETE_ORDER_STATUS = "DELETE_ORDER_STATUS";
export const ORDER_STATUS_LOADING = "ORDER_STATUS_LOADING";
export const ORDER_STATUS_ERROR = "ORDER_STATUS_ERROR";
export const ORDER_STATUS_SUCCESS = "ORDER_STATUS_SUCCESS";

// Order Payments
export const GET_ORDER_PAYMENTS = "GET_ORDER_PAYMENTS";
export const CREATE_ORDER_PAYMENT = "CREATE_ORDER_PAYMENT";
export const ORDER_PAYMENT_LOADING = "ORDER_PAYMENT_LOADING";
export const ORDER_PAYMENT_SUCCESS = "ORDER_PAYMENT_SUCCESS";
export const ORDER_PAYMENT_ERROR = "ORDER_PAYMENT_ERROR";

// Incentives
export const GET_INCENTIVES = "GET_INCENTIVES";
export const INCENTIVE_LOADING = "INCENTIVE_LOADING";
export const INCENTIVE_SUCCESS = "INCENTIVE_SUCCESS";
export const INCENTIVE_ERROR = "INCENTIVE_ERROR";

// Invoice
export const GET_INVOICES = "GET_INVOICES";
export const ADD_INVOICE = "ADD_INVOICE";
export const UPDATE_INVOICE = "UPDATE_INVOICE";
export const DELETE_INVOICE = "DELETE_INVOICE";
export const INVOICE_LOADING = "INVOICE_LOADING";
export const INVOICE_SUCCESS = "INVOICE_SUCCESS";
export const INVOICE_ERROR = "INVOICE_ERROR";

// Ticket Service
export const GET_TICKET_SERVICE = "GET_TICKET_SERVICE";
export const ADD_TICKET_SERVICE = "ADD_TICKET_SERVICE"; 
export const UPDATE_TICKET_SERVICE = "UPDATE_TICKET_SERVICE";
export const DELETE_TICKET_SERVICE = "DELETE_TICKET_SERVICE";
export const TICKET_SERVICE_LOADING = "TICKET_SERVICE_LOADING";
export const TICKET_SERVICE_SUCCESS = "TICKET_SERVICE_SUCCESS";
export const TICKET_SERVICE_ERROR = "TICKET_SERVICE_ERROR";

// Ticket Priority
export const GET_TICKET_PRIORITY = "GET_TICKET_PRIORITY";
export const ADD_TICKET_PRIORITY = "ADD_TICKET_PRIORITY";
export const UPDATE_TICKET_PRIORITY = "UPDATE_TICKET_PRIORITY";
export const DELETE_TICKET_PRIORITY = "DELETE_TICKET_PRIORITY";
export const TICKET_PRIORITY_LOADING = "TICKET_PRIORITY_LOADING";
export const TICKET_PRIORITY_SUCCESS = "TICKET_PRIORITY_SUCCESS";
export const TICKET_PRIORITY_ERROR = "TICKET_PRIORITY_ERROR";

// Ticket
export const GET_TICKETS = "GET_TICKETS";
export const ADD_TICKET = "ADD_TICKET";
export const UPDATE_TICKET = "UPDATE_TICKET";
export const DELETE_TICKET = "DELETE_TICKET";
export const TICKET_LOADING = "TICKET_LOADING";
export const TICKET_SUCCESS = "TICKET_SUCCESS";
export const TICKET_ERROR = "TICKET_ERROR";

// Package
export const GET_PACKAGES = "GET_PACKAGES"; 
export const GET_PACKAGE_BY_ID = "GET_PACKAGE_BY_ID"; 
export const ADD_PACKAGE = "ADD_PACKAGE";
export const UPDATE_PACKAGE = "UPDATE_PACKAGE";
export const DELETE_PACKAGE = "DELETE_PACKAGE";
export const PACKAGE_LOADING = "PACKAGE_LOADING";
export const PACKAGE_SUCCESS = "PACKAGE_SUCCESS";
export const PACKAGE_ERROR = "PACKAGE_ERROR";

// API Master
export const GET_APIS = "GET_APIS";
export const ADD_API = "ADD_API";
export const UPDATE_API = "UPDATE_API";
export const DELETE_API = "DELETE_API";
export const API_LOADING = "API_LOADING";
export const API_SUCCESS = "API_SUCCESS";
export const API_ERROR = "API_ERROR";
export const GET_API_LEADS = "GET_API_LEADS"
export const UPDATE_LEAD_STATUS = "UPDATE_LEAD_STATUS"

// Customer Category
export const GET_CUSTOMER_CATEGORY = "GET_CUSTOMER_CATEGORY";
export const ADD_CUSTOMER_CATEGORY = "ADD_SALUTATION";
export const UPDATE_CUSTOMER_CATEGORY = "UPDATE_CUSTOMER_CATEGORY";
export const DELETE_CUSTOMER_CATEGORY = "DELETE_CUSTOMER_CATEGORY";
export const CUSTOMER_CATEGORY_LOADING = "CUSTOMER_CATEGORY_LOADING";
export const CUSTOMER_CATEGORY_ERROR = "CUSTOMER_CATEGORY_ERROR";
export const CUSTOMER_CATEGORY_SUCCESS = "CUSTOMER_CATEGORY_SUCCESS";

// Industry
export const GET_INDUSTRY = "GET_INDUSTRY";
export const ADD_INDUSTRY = "ADD_INDUSTRY";
export const UPDATE_INDUSTRY = "UPDATE_INDUSTRY";
export const DELETE_INDUSTRY = "DELETE_INDUSTRY";
export const INDUSTRY_LOADING = "INDUSTRY_LOADING";
export const INDUSTRY_ERROR = "INDUSTRY_ERROR";
export const INDUSTRY_SUCCESS = "INDUSTRY_SUCCESS";

// shared
export const CLEAR_SNACKBAR = "CLEAR_SNACKBAR";

export const GET_DASHBOARD_DATA = "GET_DASHBOARD_DATA";
export const DASHBOARD_LOADING = "DASHBOARD_LOADING";

export const GET_PROVIDER_DASHBOARD_DATA = "GET_PROVIDER_DASHBOARD_DATA";
export const PROVIDER_DASHBOARD_LOADING = "PROVIDER_DASHBOARD_LOADING";

// Landing Page Leads
export const GET_LANDING_LEADS = "GET_LANDING_LEADS";
export const UPDATE_LANDING_LEAD_STATUS = "UPDATE_LANDING_LEAD_STATUS";
export const LANDING_LEAD_LOADING = "LANDING_LEAD_LOADING";
export const LANDING_LEAD_SUCCESS = "LANDING_LEAD_SUCCESS";
export const LANDING_LEAD_ERROR = "LANDING_LEAD_ERROR";

export const GET_PREFIX = "GET_PREFIX";
export const UPSERT_PREFIX = "UPSERT_PREFIX";
export const DELETE_PREFIX = "DELETE_PREFIX";
export const PREFIX_LOADING = "PREFIX_LOADING";
export const PREFIX_SUCCESS = "PREFIX_SUCCESS";
export const PREFIX_ERROR = "PREFIX_ERROR";

// Notification types
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_FAIL = 'FETCH_NOTIFICATIONS_FAIL';
export const MARK_READ_SUCCESS = 'MARK_READ_SUCCESS';
export const MARK_READ_FAIL = 'MARK_READ_FAIL';
export const MARK_ALL_READ_SUCCESS = 'MARK_ALL_READ_SUCCESS';
export const MARK_ALL_READ_FAIL = 'MARK_ALL_READ_FAIL';
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS';
export const DELETE_NOTIFICATION_FAIL = 'DELETE_NOTIFICATION_FAIL';
export const GET_UNREAD_COUNT_SUCCESS = 'GET_UNREAD_COUNT_SUCCESS';
export const GET_UNREAD_COUNT_FAIL = 'GET_UNREAD_COUNT_FAIL';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const NOTIFICATION_LOADING = 'NOTIFICATION_LOADING';
export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR';

// Bank Details
export const GET_BANKS = "GET_BANKS";
export const GET_BANK_BY_ID = "GET_BANK_BY_ID";
export const ADD_BANK = "ADD_BANK";
export const UPDATE_BANK = "UPDATE_BANK";
export const DELETE_BANK = "DELETE_BANK";
export const BANK_LOADING = "BANK_LOADING";
export const BANK_SUCCESS = "BANK_SUCCESS";
export const BANK_ERROR = "BANK_ERROR";
export const CLEAR_BANK = "CLEAR_BANK";

// T&C and Description Types
export const GET_T_AND_C_AND_DEC = "GET_T_AND_C_AND_DEC";
export const ADD_T_AND_C_AND_DEC = "ADD_T_AND_C_AND_DEC";
export const UPDATE_T_AND_C_AND_DEC = "UPDATE_T_AND_C_AND_DEC";
export const DELETE_T_AND_C_AND_DEC = "DELETE_T_AND_C_AND_DEC";
export const T_AND_C_AND_DEC_ERROR = "T_AND_C_AND_DEC_ERROR";
export const T_AND_C_AND_DEC_SUCCESS = "T_AND_C_AND_DEC_SUCCESS";
export const T_AND_C_AND_DEC_LOADING = "T_AND_C_AND_DEC_LOADING";
export const GET_DEFAULT_T_AND_C_AND_DEC = "GET_DEFAULT_T_AND_C_AND_DEC";